src/main/java/com/hz/entity/cemetery/Cemetery.java
package com.hz.entity.cemetery;

import java.sql.Timestamp;

import com.hz.util.Const;

/**
 * 陵园信息表
 * @author jgj
 */
public class Cemetery {
	//陵园id
	private String id;
	//别名
	private String name;
	//创建时间
	private Timestamp createTime;
	//创建人
	private String createPeople;
	//陵园地址
	private String address;
	//照片地址
	private String photo;
	//顺序号
	private int index;
	//启用标志
	private byte isdel;
	
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getPhoto() {
		return photo;
	}
	public void setPhoto(String photo) {
		this.photo = photo;
	}
	public int getIndex() {
		return index;
	}
	public void setIndex(int index) {
		this.index = index;
	}
	public byte getIsdel() {
		return isdel;
	}
	public void setIsdel(byte isdel) {
		this.isdel = isdel;
	}
	public Timestamp getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}
	public String getCreatePeople() {
		return createPeople;
	}
	public void setCreatePeople(String createPeople) {
		this.createPeople = createPeople;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	
	/**
	 * 是否启用标志
	 * @return
	 */
	public String getIsdelName(){
		return Const.getIsdel(this.isdel);
		
	}
}

src/main/java/com/hz/entity/cemetery/RepairRecord.java
package com.hz.entity.cemetery;

import com.hz.util.Const;

import java.sql.Date;


/**
 * 墓穴维修记录
 *
 * @author jgj
 */
public class RepairRecord {
    //id
    private String id;
    //维修报备人
    private String name;
    //联系电话
    private String phoneNumber;
    //维修内容
    private String comment;
    //开始时间
    private Date beginTime;
    //预计结束时间
    private Date endTime;
    //维修完成时间
    private Date completeTime;
    //维修墓穴ID
    private String tombId;
    //维修状态
    private byte repairType;
    //维修墓穴信息
    private Tomb tomb;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Date getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public Date getCompleteTime() {
        return completeTime;
    }

    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    public String getTombId() {
        return tombId;
    }

    public void setTombId(String tombId) {
        this.tombId = tombId;
    }

    public byte getRepairType() {
        return repairType;
    }

    public void setRepairType(byte repairType) {
        this.repairType = repairType;
    }

    public Tomb getTomb() {
        return tomb;
    }

    public void setTomb(Tomb tomb) {
        this.tomb = tomb;
    }

    /**
     * 是否维修标志
     *
     * @return
     */
    public String getIsRepairName() {
        return Const.getIsRepair(this.repairType);
    }
}

src/main/java/com/hz/entity/cemetery/Tomb.java
package com.hz.entity.cemetery;

import com.hz.util.Const;

import java.sql.Date;

/**
 * 墓穴信息表
 *
 * @author jgj
 */
public class Tomb {
    //墓穴id
    private String id;
    //别名
    private String name;
    //所属排ID
    private String rowId;
    //照片地址
    private String photo;
    //单价
    private double price;
    //状态
    private byte state;
    //顺序号
    private int index;
    //启用标志
    private byte isdel;
    //描述
    private String comment;
    //维护费
    private double maintenance;
    //排名称
    private String rowName;
    //操作人
    private String opertor;
    //墓区id
    private String areaId;
    //排序号
    private String number;
    //陵园id
    private String cId;
    //实际销售价格
    private float salePrice;
    //到期时间
    private Date expireDate;
    //创建时间
    private Date creatime;
    //排中排
    private int row2;

    public double getMaintenance() {
        return maintenance;
    }

    public void setMaintenance(double maintenance) {
        this.maintenance = maintenance;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRowId() {
        return rowId;
    }

    public void setRowId(String rowId) {
        this.rowId = rowId;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public byte getState() {
        return state;
    }

    public void setState(byte state) {
        this.state = state;
    }

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public byte getIsdel() {
        return isdel;
    }

    public void setIsdel(byte isdel) {
        this.isdel = isdel;
    }

    public String getRowName() {
        return rowName;
    }

    public void setRowName(String rowName) {
        this.rowName = rowName;
    }

    public String getOpertor() {
        return opertor;
    }

    public void setOpertor(String opertor) {
        this.opertor = opertor;
    }

    public String getAreaId() {
        return areaId;
    }

    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getcId() {
        return cId;
    }

    public void setcId(String cId) {
        this.cId = cId;
    }

    public float getSalePrice() {
        return salePrice;
    }

    public void setSalePrice(float salePrice) {
        this.salePrice = salePrice;
    }

    public Date getExpireDate() {
        return expireDate;
    }

    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    public Date getCreatime() {
        return creatime;
    }

    public void setCreatime(Date creatime) {
        this.creatime = creatime;
    }

    public int getRow2() {
        return row2;
    }

    public void setRow2(int row2) {
        this.row2 = row2;
    }

    /**
     * 是否启用标志
     *
     * @return
     */
    public String getIsdelName() {
        return Const.getIsdel(this.isdel);
    }

    /**
     * 获取状态名称
     *
     * @return
     */
    public String getStateName() {
        return Const.getState(this.state);
    }
}

src/main/java/com/hz/entity/cemetery/TransferRecord.java
package com.hz.entity.cemetery;

import com.hz.util.Const;

import java.sql.Date;


/**
 * 墓穴迁出记录
 *
 * @author jgj
 */
public class TransferRecord {
    //id
    private String id;
    //申请人
    private String applicant;
    //申请人电话
    private String phoneNumber;
    //迁出人姓名
    private String userName;
    //迁出时间
    private Date transferTime;
    //操作时间
    private Date createTime;
    //操作人
    private String createPeople;
    //预约墓穴ID
    private String tombId;
    //备注信息
    private String comment;
    //是否回收墓穴证
    private byte isRecovery;


    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getApplicant() {
        return applicant;
    }

    public void setApplicant(String applicant) {
        this.applicant = applicant;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Date getTransferTime() {
        return transferTime;
    }

    public void setTransferTime(Date transferTime) {
        this.transferTime = transferTime;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getCreatePeople() {
        return createPeople;
    }

    public void setCreatePeople(String createPeople) {
        this.createPeople = createPeople;
    }

    public String getTombId() {
        return tombId;
    }

    public void setTombId(String tombId) {
        this.tombId = tombId;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public byte getIsRecovery() {
        return isRecovery;
    }

    public void setIsRecovery(byte isRecovery) {
        this.isRecovery = isRecovery;
    }

    /**
     * 获取是否回收墓穴证名称
     *
     * @return
     */
    public String getIsRecoveryName() {
        return Const.getIsRecovery(this.isRecovery);
    }
}

src/main/java/com/hz/entity/cemetery/UserRecord.java
package com.hz.entity.cemetery;

import java.sql.Date;

import com.hz.util.Const;


/**
 * 墓穴使用者记录
 *
 * @author jgj
 */
public class UserRecord {
    /**
     * 使用记录ID
     */
    private String id;
    /**
     * 使用者姓名
     */
    private String userName;
    /**
     * 死亡类型
     */
    private byte deadType;
    /**
     * 性别
     */
    private byte sex;
    /**
     * 生于时间
     */
    private Date borthTime;
    /**
     * 死亡时间
     */
    private Date deadTime;
    /**
     * 封龙门时间
     */
    private Date longmenTime;
    /**
     * 安置时间
     */
    private Date releaseTime;
    /**
     * 墓穴ID
     */
    private String tombId;
    /**
     * 购买记录ID
     */
    private String buyRecordId;
    /**
     * 是否迁移
     */
    private byte isTransfer;
    /**
     * 购买记录
     */
    private BuyRecord buyRecord;
    /**
     * 墓穴信息
     */
    private Tomb tomb;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public byte getDeadType() {
        return deadType;
    }

    public void setDeadType(byte deadType) {
        this.deadType = deadType;
    }

    public byte getSex() {
        return sex;
    }

    public void setSex(byte sex) {
        this.sex = sex;
    }

    public Date getBorthTime() {
        return borthTime;
    }

    public void setBorthTime(Date borthTime) {
        this.borthTime = borthTime;
    }

    public Date getDeadTime() {
        return deadTime;
    }

    public void setDeadTime(Date deadTime) {
        this.deadTime = deadTime;
    }

    public Date getLongmenTime() {
        return longmenTime;
    }

    public void setLongmenTime(Date longmenTime) {
        this.longmenTime = longmenTime;
    }

    public Date getReleaseTime() {
        return releaseTime;
    }

    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    public String getTombId() {
        return tombId;
    }

    public void setTombId(String tombId) {
        this.tombId = tombId;
    }

    public String getBuyRecordId() {
        return buyRecordId;
    }

    public void setBuyRecordId(String buyRecordId) {
        this.buyRecordId = buyRecordId;
    }

    public byte getIsTransfer() {
        return isTransfer;
    }

    public void setIsTransfer(byte isTransfer) {
        this.isTransfer = isTransfer;
    }

    public BuyRecord getBuyRecord() {
        return buyRecord;
    }

    public void setBuyRecord(BuyRecord buyRecord) {
        this.buyRecord = buyRecord;
    }

    public Tomb getTomb() {
        return tomb;
    }

    public void setTomb(Tomb tomb) {
        this.tomb = tomb;
    }

    /**
     * 获取性别名称
     *
     * @return
     */
    public String getSexName() {
        return Const.getSex(this.sex);
    }

    /**
     * 获取是否迁移名称
     *
     * @return
     */
    public String getIsTransferName() {
        return Const.getIs(this.isTransfer);
    }

    /**
     * 获取公墓死者死亡类型名称
     *
     * @return
     */
    public String getDeadTypeName() {
        return Const.getDeadType(this.deadType);
    }

}

src/main/java/com/hz/controller/cemetery/index/CemeteryInterfaceController.java
package com.hz.controller.cemetery.index;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import com.alibaba.fastjson.JSONObject;
import com.github.pagehelper.PageInfo;
import com.hz.annotation.SystemControllerLog;
import com.hz.controller.system.BaseController;
import com.hz.entity.cemetery.AppointmentRecord;
import com.hz.entity.cemetery.BuyRecord;
import com.hz.entity.cemetery.Cemetery;
import com.hz.service.cemetery.AppointmentRecordService;
import com.hz.service.cemetery.BuyRecordService;
import com.hz.service.cemetery.CemeteryService;
import com.hz.util.Const;

/**
 * 陵园主界面--效果等同6.2系统界面
 *
 * @author jgj
 */
@Controller
@RequestMapping("/cemeteryInterface.do")
public class CemeteryInterfaceController extends BaseController {
    @Autowired
    private CemeteryService cemeteryService;
    @Autowired
    private BuyRecordService buyRecordService;
    @Autowired
    private AppointmentRecordService appointmentRecordService;

    @ModelAttribute
    public void CemeteryModel(Model model) {
        model.addAttribute("url", "cemeteryInterface.do");
    }

    @RequestMapping
    public ModelAndView unspecified() {
        return listCemetery();
    }

    /**
     * 陵园信息查询列表
     *
     * @return
     */
    @RequestMapping(params = "method=list")
    public ModelAndView listCemetery() {
        Map<String, Object> model = new HashMap<String, Object>();
        model = getModel(model);
        // 填入查询内容
        Map<String, Object> maps = new HashMap<String, Object>();
        // 状态为启用
        maps.put("isdel", Const.Isdel_No);
        List<Cemetery> list = cemeteryService.getCemeteryList(maps, "");
        model.put("method", "list");
        model.put("cemetery", list);
        return new ModelAndView("cemetery/cemeteryInterface/cemeteryInterface", model);
    }

    /**
     * 墓穴购买记录
     *
     * @return
     */
    @RequestMapping(params = "method=tombPayRecord")
    public ModelAndView tombPayRecord() {
        Map<String, Object> model = new HashMap<String, Object>();
        // 获得页面页码信息
        int[] pages = getPage();
        model = getModel(model);
        PageInfo<BuyRecord> page = buyRecordService.getBuyRecordPageInfo(null, pages[0], pages[1], null);
        model.put("page", page);
        model.put("method", "save");
        model.put("url", "cemeteryInterface.do");
        return new ModelAndView("cemetery/cemeteryInterface/listAppointmentRecord", model);
    }

    /**
     * 墓穴预约记录
     *
     * @return
     */
    @RequestMapping(params = "method=appointmentRecord")
    public ModelAndView appointmentRecord() {
        Map<String, Object> model = new HashMap<String, Object>();
        // 获得页面页码信息
        int[] pages = getPage();
        model = getModel(model);
        PageInfo<AppointmentRecord> page = appointmentRecordService.getAppointmentRecordPageInfo(null, pages[0], pages[1], null);
        model.put("page", page);
        model.put("method", "save");
        model.put("url", "cemeteryInterface.do");
        return new ModelAndView("cemetery/cemeteryInterface/listAppointmentRecord", model);
    }

    /**
     * 删除陵园信息
     *
     * @return
     */
    @RequestMapping(params = "method=delete")
    @SystemControllerLog(description = "删除陵园信息")
    @ResponseBody
    public JSONObject deleteCemetery() {
        JSONObject json = new JSONObject();
        try {
            String id = getString("ids");
            cemeteryService.deleteCemetery(id);
            setJsonBySuccess(json, "删除成功", true);
        } catch (Exception e) {
            setJsonByFail(json, "删除失败，错误" + e.getMessage());
        }
        return json;
    }

}

src/main/webapp/WEB-INF/jsp/cemetery/cemetery/sale/cemeteryCarving.jsp
<%--
  Created by IntelliJ IDEA.
  User: ZhixiangWang
  Date: 2019/6/27
  Time: 21:09
  To change this template use File | Settings | File Templates.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="/common/common.jsp" %>

<section class="content-header">
    <i class="title-line"></i>
    <div class="title">安放查询</div>
    <div class="pull-right">
        <a href="cemeteryInterface.do" target="homeTab" rel="myModal" class="btn btn-warning" role="button">返回首页</a>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">当前所在位置：
                        <a href="cemeteryInterface.do?" target="homeTab">公墓销售</a>/
                        <a href="" target="homeTab">安放</a>
                    </h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool"
                                data-widget="collapse">
                            <i class="fa fa-chevron-down"></i>
                        </button>
                    </div>
                    <!-- /.box-tools -->
                </div>
                <!-- /.box-header -->
                <form action="${url }" id="pageForm" onsubmit="return homeSearch(this);">
                    <%@ include file="/common/pageHead.jsp" %>
                    <input name="method" value="${method}" type="hidden"/>
                    <input name="type" value="1" type="hidden"/>
                    <div class="box-body">
                        <div class="col-md-2">
                            <label>类型：</label>
                            <select class="list_select nopadding-R" name="searchType" id="searchType"
                                    style="width: 60%;">
                                <option value="1">姓名</option>
                                <option value="2">家属</option>
                                <option value="3">墓位名称</option>
                            </select>
                        </div>
                        <div class="col-md-2">
                            <label>条件：</label>
                            <select class="list_select nopadding-R" name="searchCondition" id="searchCondition"
                                    style="width: 60%;">
                                <option value="a1">包含</option>
                                <option value="a2">不包含</option>
                                <option value="b1">等于</option>
                                <option value="b2">不等于</option>
                            </select>
                        </div>
                        <div class="col-md-5">
                            <label>查询值：</label>
                            <input type="text" class="list_input" name="searchVal" id="searchVal" value="${searchVal}"
                                   placeholder="查询值">
                        </div>
                        <div class="col-md-2">
                            <button type="submit" class="btn btn-info btn-search">搜索</button>
                        </div>
                    </div>
                </form>
            </div>
            <!-- /.col -->
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box" style="border-top: 0">
                <!-- /.box-header -->
                <div class="box-body">
                    <div id="example2_wrapper"
                         class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-bordered table-hover">
                                    <thead>
                                    <tr role="row">
                                        <th>姓名</th>
                                        <th>性别</th>
                                        <th>寿故</th>
                                        <th>家属</th>
                                        <th>安放时间</th>
                                        <th>墓位名称</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <c:choose>
                                        <c:when test="${fn:length(page.list)==0 }">
                                            <tr>
                                                <td colspan="6">
                                                    <font color="Red">还没有数据</font>
                                                </td>
                                            </tr>
                                        </c:when>
                                        <c:otherwise>
                                            <c:forEach items="${page.list }" var="u">
                                                <tr role="row">
                                                    <td>${u.userName }</td>
                                                    <td>${u.sexName }</td>
                                                    <td>${u.deadTypeName }</td>
                                                    <td></td>
                                                    <td>
                                                        <fmt:formatDate value="${u.releaseTime }"
                                                                        pattern="yyyy-MM-dd HH:mm"/>
                                                    </td>
                                                    <td>
                                                        <a href="tombType.do?method=list&tid=${u.buyRecord.tombId }&cemeteryId=${u.tomb.cId}&areaId=${u.tomb.areaId}"
                                                           target='homeTab'>${u.buyRecord.graveInfo }</a></td>
                                                </tr>
                                            </c:forEach>
                                        </c:otherwise>
                                    </c:choose>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <%@ include file="/common/pageFood.jsp" %>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>
<script>
    $(function () {
        if (${searchType != '' && searchCondition != ''}) {
            $("#searchType").val("${searchType}");
            $("#searchCondition").val("${searchCondition}");
        }
        setTimeout(() => {
            if (${entries != ''}) {
                $("#searchType").val("1");
                $("#searchCondition").val("a1");
                $("#searchVal").val("");
            }
        }, 0);
    });
</script>

src/main/webapp/WEB-INF/jsp/cemetery/cemetery/sale/userRecord.jsp
<%--
  Created by IntelliJ IDEA.
  User: ZhixiangWang
  Date: 2019/6/27
  Time: 17:48
  To change this template use File | Settings | File Templates.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="/common/common.jsp" %>

<section class="content-header">
    <i class="title-line"></i>
    <div class="title">使用者查询</div>
    <div class="pull-right">
        <a href="cemeteryInterface.do" target="homeTab" rel="myModal" class="btn btn-warning" role="button">返回首页</a>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">当前所在位置：
                        <a href="cemeteryInterface.do?" target="homeTab">公墓销售</a>/
                        <a href="" target="homeTab">使用者</a>
                    </h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool"
                                data-widget="collapse">
                            <i class="fa fa-chevron-down"></i>
                        </button>
                    </div>
                    <!-- /.box-tools -->
                </div>
                <!-- /.box-header -->
                <form action="${url }" id="pageForm" onsubmit="return homeSearch(this);">
                    <%@ include file="/common/pageHead.jsp" %>
                    <input name="method" value="${method}" type="hidden"/>
                    <div class="box-body">
                        <div class="col-md-2">
                            <label>类型：</label>
                            <select class="list_select nopadding-R" name="searchType" id="searchType"
                                    style="width: 68%;">
                                <option value="1">姓名</option>
                                <option value="3">墓位名称</option>
                                <option value="4">持证人姓名</option>
                            </select>
                        </div>
                        <div class="col-md-2">
                            <label>条件：</label>
                            <select class="list_select nopadding-R" name="searchCondition" id="searchCondition"
                                    style="width: 60%;">
                                <option value="a1">包含</option>
                                <option value="a2">不包含</option>
                                <option value="b1">等于</option>
                                <option value="b2">不等于</option>
                            </select>
                        </div>
                        <div class="col-md-5">
                            <label>查询值：</label>
                            <input type="text" class="list_input" name="searchVal" id="searchVal" value="${searchVal}"
                                   placeholder="查询值">
                        </div>
                        <div class="col-md-2">
                            <button type="submit" class="btn btn-info btn-search">搜索</button>
                        </div>
                    </div>
                </form>
            </div>
            <!-- /.col -->
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box" style="border-top: 0">
                <!-- /.box-header -->
                <div class="box-body">
                    <div id="example2_wrapper"
                         class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-bordered table-hover">
                                    <thead>
                                    <tr role="row">
                                        <th>姓名</th>
                                        <th>性别</th>
                                        <th>寿故</th>
                                        <th>墓位名称</th>
                                        <th>持证人姓名</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <c:choose>
                                        <c:when test="${fn:length(page.list)==0 }">
                                            <tr>
                                                <td colspan="5">
                                                    <font color="Red">还没有数据</font>
                                                </td>
                                            </tr>
                                        </c:when>
                                        <c:otherwise>
                                            <c:forEach items="${page.list }" var="u">
                                                <tr role="row">
                                                    <td>${u.userName }</td>
                                                    <td>${u.sexName }</td>
                                                    <td>${u.deadTypeName }</td>
                                                    <td>
                                                        <a href="tombType.do?method=list&tid=${u.buyRecord.tombId }&cemeteryId=${u.tomb.cId}&areaId=${u.tomb.areaId}"
                                                           target='homeTab'>${u.buyRecord.graveInfo }</a></td>
                                                    <td>${u.buyRecord.cardHolder }</td>
                                                </tr>
                                            </c:forEach>
                                        </c:otherwise>
                                    </c:choose>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <%@ include file="/common/pageFood.jsp" %>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>
<script>
    $(function () {
        if (${searchType != '' && searchCondition != ''}) {
            $("#searchType").val("${searchType}");
            $("#searchCondition").val("${searchCondition}");
        }
        setTimeout(() => {
            if (${entries != ''}) {
                $("#searchType").val("1");
                $("#searchCondition").val("a1");
                $("#searchVal").val("");
            }
        }, 0);
    });
</script>